version: '3.8'

services:
  example:
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/code
    # prod
    # command: uv run fastapi run app/main.py --port 80
    # dev
    command: uv run fastapi dev app/main.py --host 0.0.0.0 --port 80